# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ddcc95f4a9909a41f99c1eb37ec1ea8a1b5ecde5fd78aa1989c1705582833ca646aa5d2c633236ce7bfa94e996ca717eed2f34fbe790a1f3cec4247fa7d1d49

test:
  secret_key_base: 235c482628b347a765f63193187254652133935299cac69199b2f92e084724361917d1d463a43de46e7def6de188562aeafea0d3dc8eed67d2ff392713cb7ec8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
